// src/data/serviceData.js

const serviceData = [
    {
      id: 1,
      title: "Web Development",
      category: "Technology",
      name: "John Doe",
      rating: "4.9",
      status: "Available Now",
      experience: "8 Years",
      projects: "120+",
      rate: "$75/hr",
      description: "Expert web development services including responsive design, e-commerce solutions, and custom web applications.",
      profilePic: "https://th.bing.com/th/id/OIP.JW6y66WKmf6zdRCs_zulfQHaFY?w=1024&h=745&rs=1&pid=ImgDetMain",
    },
    {
      id: 2,
      title: "UI/UX Design",
      category: "Design",
      name: "Jane Smith",
      rating: "4.8",
      status: "Available Today",
      experience: "6 Years",
      projects: "85+",
      rate: "$65/hr",
      description: "Professional UI/UX design services with focus on user-centered design principles and modern aesthetics.",
      profilePic: "https://th.bing.com/th/id/OIP.NqY3rNMnx2NXYo3KJfg43gHaHa?w=1080&h=1080&rs=1&pid=ImgDetMain",
    },
    {
      id: 3,
      title: "Digital Marketing",
      category: "Marketing",
      name: "Mike Johnson",
      rating: "4.7",
      status: "Available Next Week",
      experience: "5 Years",
      projects: "95+",
      rate: "$55/hr",
      description: "Comprehensive digital marketing services including SEO, social media management, and content strategy.",
      profilePic: "https://th.bing.com/th/id/OIP.NqY3rNMnx2NXYo3KJfg43gHaHa?w=1080&h=1080&rs=1&pid=ImgDetMain",
    },
    {
      id: 3,
      title: "Digital Marketing",
      category: "Marketing",
      name: " Johnson",
      rating: "4.7",
      status: "Available Next Week",
      experience: "5 Years",
      projects: "95+",
      rate: "$55/hr",
      description: "Comprehensive digital marketing services including SEO, social media management, and content strategy.",
      profilePic: "https://th.bing.com/th/id/OIP.NqY3rNMnx2NXYo3KJfg43gHaHa?w=1080&h=1080&rs=1&pid=ImgDetMain",
    },
    {
      id: 3,
      title: "Digital Marketing",
      category: "Marketing",
      name: "Mike Johnson",
      rating: "4.7",
      status: "Available Next Week",
      experience: "5 Years",
      projects: "95+",
      rate: "$55/hr",
      description: "Comprehensive digital marketing services including SEO, social media management, and content strategy.",
      profilePic: "https://th.bing.com/th/id/OIP.NqY3rNMnx2NXYo3KJfg43gHaHa?w=1080&h=1080&rs=1&pid=ImgDetMain",
    },
    {
      id: 3,
      title: "Digital Marketing",
      category: "Marketing",
      name: "Mike Johnson",
      rating: "4.7",
      status: "Available Next Week",
      experience: "5 Years",
      projects: "95+",
      rate: "$55/hr",
      description: "Comprehensive digital marketing services including SEO, social media management, and content strategy.",
      profilePic: "https://th.bing.com/th/id/OIP.NqY3rNMnx2NXYo3KJfg43gHaHa?w=1080&h=1080&rs=1&pid=ImgDetMain",
    },
  ];
  
  export default serviceData;
  