name: ZAP-MVP CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    name: Backend Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend tests
      run: echo "Run your backend tests here"

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FrontendApp

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: npm install --legacy-peer-deps  # Add this flag to bypass peer dependency issues

    - name: Install Expo dependencies
      run: npx expo install react-dom react-native-web @expo/metro-runtime @expo/webpack-config
           

    - name: Run tests
      run: npm test --if-present

    - name: Build frontend
      run: npm run build
